# This is a basic workflow to help you get started with Actions

name: download-test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    # Sequence of patterns matched against refs/heads
    #branches:    
      # Push events on main branch
    #  - master
      # Push events to release branches
    #  - 'release/**'
      # Push events to release branches
    #  - 'hotfix/**'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: FranzDiebold/github-env-vars-action@v1.2.0
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Gather Download urls
      run: grep "http://linuxgsm.download" lgsm/functions/install_server_files.sh | tee download-urls.txt
