# This is a basic workflow to help you get started with Actions

name: rustserver

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
          node-version: '14'
    - run: npm install gamedig -g
    # Runs a single command using the runners shell
    - name: linuxgsm.sh pre-test setup
      run: chmod +x lgsm/functions/*
    - name: ./linuxgsm.sh (get-opt)
      run: bash ./linuxgsm.sh
    - name: ./linuxgsm.sh list
      run: bash ./linuxgsm.sh list
    - name: ./linuxgsm.sh rustserver
      run: bash ./linuxgsm.sh rustserver
    - name: ./rustserver (get-opt)
      run: bash ./rustserver
    - name: ./rustserver dev
      run: bash ./rustserver dev
    # Install
    - name: ./rustserver auto-install
      run: bash ./rustserver auto-install
    # Speed up messages
    - name: Speed up message display
      run: echo "sleeptime=\"0.1\"" > lgsm/config-lgsm/rustserver/common.cfg
    # Start. Stop, Restart
    - name: ./rustserver start
      run: bash ./rustserver start
    - name: ./rustserver start (already online)
      run: bash .github/exitcode.sh "./rustserver start" "2"
    - name: ./rustserver restart
      run: bash ./rustserver restart
    - name: ./rustserver stop
      run: bash ./rustserver stop
    - name: ./rustserver restart (server offline)
      run: bash ./rustserver restart
    # update
    - name: ./rustserver update (no update required)
      run: bash ./rustserver update
    - name: ./rustserver update (update required - online)
      run: |
        sed -i 's/[0-9]\+/0/' "serverfiles/steamapps/appmanifest_258550.acf"
        bash ./rustserver update
    - name: ./rustserver update (remove appmanifest file)
      run: |
        rm --verbose "serverfiles/steamapps/appmanifest_258550.acf"
        bash ./rustserver update
    - name: ./rustserver force-update (offline)
      run: bash ./rustserver force-update
    - name: ./rustserver force-update (online)
      run: |
        bash ./rustserver start
        bash ./rustserver update
    - name: ./rustserver validate (online)
      run: bash ./rustserver validate
    - name: Simulate out-of-date modules
      run: |
        echo "#test" >> lgsm/tmp/linuxgsm.sh
        echo "#test" >> lgsm/config-default/config-lgsm/rustserver/_default.cfg
        echo "#test" >> lgsm/functions/alert.sh
    - name: ./rustserver update-lgsm
      run: bash ./rustserver update-lgsm
    # monitor
    - name: ./rustserver monitor (offline)
      run: bash .github/exitcode.sh "./rustserver monitor" "2"
    - name: ./rustserver monitor (offline with lockfile)
      run: |
        date '+%s' > "lgsm/lock/rustserver.lock"
        bash ./rustserver monitor
    - name: ./rustserver monitor (online)
      run: |
        bash ./rustserver monitor
    - name: ./rustserver test-alert
      run: |
        bash .github/exitcode.sh "./rustserver test-alert" "3"
    # details
    - name: ./rustserver details
      run: bash ./rustserver details
    - name: ./rustserver postdetails
      run: bash ./rustserver postdetails
    # Backup
    - name: ./rustserver backup
      run: bash ./rustserver backup
    # Dev Tools
    - name: ./rustserver detect-glibc
      run: bash ./rustserver detect-glibc
    - name: ./rustserver detect-ldd
      run: bash ./rustserver detect-ldd
    - name: ./rustserver detect-deps
      run: bash ./rustserver detect-deps
    - name: ./rustserver query-raw
      run: bash ./rustserver query-raw
    # Donate
    - name: ./rustserver donate
      run: bash ./rustserver donate
